import pandas as pd
data = pd.read_csv('./Data.csv')
print("Checking for Missing Values:")
print(data.isnull().sum())
data_filled = data.fillna(value=-1)  
data_filled_pad = data.fillna(method='pad')
data_filled_bfill = data.fillna(method='bfill')
mean_values = data.mean()
data_filled_mean = data.fillna(mean_values)
max_values = data.max()
data_filled_max = data.fillna(max_values)
min_values = data.min()
data_filled_min = data.fillna(min_values)
data_dropped = data.dropna()  #any row jis mai atleast one null will be deleted
data_replaced = data.replace(to_replace=11, value=0)  
data_interpolated = data.interpolate()
print("\nSample of Filled Values:")
print(data_filled.head())
print("\nSample of Filled Values (pad):")
print(data_filled_pad.head())
print("\nSample of Filled Values (bfill):")
print(data_filled_bfill.head())
print("\nSample of Filled Values (mean):")
print(data_filled_mean.head())
print("\nSample of Filled Values (max):")
print(data_filled_max.head())
print("\nSample of Filled Values (min):")
print(data_filled_min.head())
print("\nSample of Dropped Values:")
print(data_dropped.head())
print("\nSample of Replaced Values:")
print(data_replaced.head())
print("\nSample of Interpolated Values:")
print(data_interpolated.head())
